odin-kittens/config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

  resources :kittens

end

odin-kittens/app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

odin-kittens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

odin-kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def new
		@kitten = Kitten.new
	end

	def edit
		@kitten = Kitten.find_by(id: params[:id])
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			redirect_to action: "index"
			flash.notice = "Your kitten has been created!"
		end
	end

	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json {render json: @kittens}
		end

	end

	def destroy
		@kitten = Kitten.find_by(id: params[:id])
		@kitten.destroy
		flash.notice = "Your kitten has been deleted!"
		redirect_to action: "index"

	end

	def edit
		@kitten = Kitten.find_by(id: params[:id])
	end

	def show
		@kitten = Kitten.find_by(id: params[:id])
		respond_to do |format|
			format.html
			format.json {render json: @kitten}
		end
	end

	def update
		@kitten = Kitten.find_by(id: params[:id])
		@kitten.update(kitten_params)
		flash.notice = "Your kitten has been updated!"
		if @kitten.save
			redirect_to action: "index"
		end
	end




	private

	def kitten_params
		params.require(:kitten).permit(:name, :age, :softness, :cuteness)
	end
end

odin-kittens/app/helpers/application_helper.rb
module ApplicationHelper
end

odin-kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

odin-kittens/app/views/kittens/edit.html.erb
<%= form_for(@kitten) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
</br>
	<%= f.label :age %>
	<%= f.number_field :age %>
</br>
	<%= f.label :softness %>
	<%= f.text_field :softness %>
</br>
	<%= f.label :cuteness %>
	<%= f.text_field :cuteness %>
</br>

<%= f.submit "Submit" %>
<% end %>

odin-kittens/app/views/kittens/index.html.erb
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>
<% @kittens.each do |kitten| %>
	Name: <%= kitten.name %>
	<ol>
		<li>Age: <%= kitten.age %></li>
		<li>Softness: <%= kitten.softness %></li>
		<li>Cuteness: <%= kitten.cuteness %></li>
	</ol>

	<%= link_to "Delete kitten", kitten, method: :delete, data: {confirm: "Are you sure?"} %>
	<%= link_to "Add kitten", new_kitten_path %>
	<%= link_to "Edit kitten(how?)", edit_kitten_path(kitten) %>
	<%= link_to "Show kitten", kitten_path(kitten) %>

	</br>
	</br>

<% end %>

odin-kittens/app/views/kittens/new.html.erb
<%= form_for(@kitten) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
</br>
	<%= f.label :age %>
	<%= f.number_field :age %>
</br>
	<%= f.label :softness %>
	<%= f.text_field :softness %>
</br>
	<%= f.label :cuteness %>
	<%= f.text_field :cuteness %>
</br>

<%= f.submit "Submit" %>
<% end %>

odin-kittens/app/views/kittens/show.html.erb
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

This is Kitten number <%=@kitten.id %>
<h1>Name: <%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Softness: <%= @kitten.softness %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>